#!/bin/bash

if [ $# -ne 1 ];
	then
		printf "Se admite unicamente un parametro\n";
		exit;
fi

if [ `echo $1 | wc -L` -eq 1 ];
	then
		printf "$1 es un único caracter\n";
		if [ `echo $1 | grep "[A-Z]"` ];
			then
				printf "$1 es una letra mayúscula\n";
			elif [ `echo $1 | grep "[a-z]"` ];
				then
					printf "$1 es una letra minúscula\n";
			else
				printf "$1 no es una letra\n";
		fi
	else
		printf "$1 no es un único caracter\n";
fi
