#!/bin/bash

if [ $# != 2 ];

	then
		printf "Solo se admiten dos parametros\n";

	elif [[ $1 -eq $2 ]];

		then
			printf "$1 es igual a $2\n";

	elif [[ $1 -gt $2 ]];

		then
			printf "$1 es mayor que $2\n";

	else
			printf "$1 es menor que $2\n";

fi
